version: '3.4'
services:
  api:
    build:
      context: api
      target: dev
    volumes:
      - ./api:/app
    ports:
      - "8081:8081"
    env_file: .env-example
    # depends_on:
    #   - postgres
  client:
    build:
      context: client
      target: dev
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
  # db:
  #   build: db
  #   volumes:
  #     - ./db/migrations:/docker-entrypoint-initdb.d/migrations
  # nginx:
  #   build:
  #     context: nginx
  #     target: dev
  #   ports:
  #     - "443:443"
  #   depends_on:
  #     - client
  #     - api
